/* PollSlide — presenter interface language.
 * ---------------------------------------------------------------------------
 * The presenter's own chrome, translated. Until this existed, answer.html had 180
 * translated strings and the presenter had none — so a Spanish-speaking teacher built
 * their quiz in English and their students answered it in Spanish.
 *
 * KEYED BY THE EXACT ENGLISH STRING. `<button data-i18n>Cancel</button>` needs no
 * invented key, cannot drift out of sync with the markup, and reads as what it is.
 * A string with no entry falls through to the English in the page, so a partial
 * dictionary degrades to English rather than to a missing-key placeholder.
 *
 * NEVER TRANSLATED, and deliberately absent from every dictionary below:
 *   • "PollSlide" — the product name.
 *   • The example URL and the example email addresses — they are literal samples.
 *   • Anything a user typed. That is guaranteed structurally, not by this file:
 *     presenter.html only ever touches elements explicitly tagged `data-i18n`, so a
 *     deck title or a student's name is untouchable by construction.
 *
 * EMOJI ARE PART OF THE LABEL and are kept in place — "📊 Report" is a control people
 * recognise by its glyph before they read it, and moving or dropping the glyph makes
 * the translated UI harder to use than the English one.
 *
 * PRODUCT NOUNS: "Polly" is a name and stays. "Q&A" is kept where the language uses
 * it natively and expanded where it does not.
 */
window.PS_UI = window.PS_UI || {};
(function (D) {
  for (const l in D) { window.PS_UI[l] = Object.assign(window.PS_UI[l] || {}, D[l]); }
})({

  es: {
    '(be as specific as you like — ⌘/Ctrl+Enter to generate)': '(sé todo lo específico que quieras — ⌘/Ctrl+Intro para generar)',
    '+ Add Question': '+ Añadir pregunta',
    '+ Create New': '+ Crear nueva',
    '+ Create Your First Presentation': '+ Crea tu primera presentación',
    '+ New request': '+ Nueva solicitud',
    '0 selected': '0 seleccionadas',
    'Account': 'Cuenta',
    'Alternative: Embed in Browser / OBS / Companion': 'Alternativa: incrustar en navegador / OBS / Companion',
    'Any': 'Cualquiera',
    'Audience Q&A — questions & upvotes': 'Preguntas del público — preguntas y votos',
    'Auto': 'Automático',
    'Billing': 'Facturación',
    'Brief summary': 'Resumen breve',
    'Bug report': 'Informe de error',
    'Cancel': 'Cancelar',
    'Category': 'Categoría',
    'Close': 'Cerrar',
    'Connect in PowerPoint': 'Conectar en PowerPoint',
    'Copy Link': 'Copiar enlace',
    'Copy Question(s) To...': 'Copiar pregunta(s) a…',
    'Copy to another tab': 'Copiar a otra pestaña',
    'Decks other people have shared with you': 'Barajas que otras personas han compartido contigo',
    "Decks you've put away without deleting": 'Barajas que has guardado sin eliminar',
    'Delete': 'Eliminar',
    'Delete Presentation?': '¿Eliminar la presentación?',
    'Delete all questions for this event': 'Eliminar todas las preguntas de este evento',
    'Describe a topic and Polly drafts ready-to-go questions.': 'Describe un tema y Polly redacta preguntas listas para usar.',
    'Describe it (at least 10 characters)…': 'Descríbelo (al menos 10 caracteres)…',
    'Difficulty': 'Dificultad',
    'Drag to resize': 'Arrastra para redimensionar',
    'Duplicate': 'Duplicar',
    'Duplicate Presentation?': '¿Duplicar la presentación?',
    'Easy': 'Fácil',
    'Email address': 'Correo electrónico',
    'Email this survey': 'Enviar esta encuesta por correo',
    'Enter a new name below.': 'Escribe un nombre nuevo abajo.',
    'Everything else': 'Todo lo demás',
    'Feature request': 'Sugerencia de función',
    'Full setup guide →': 'Guía de configuración completa →',
    'Fun & casual': 'Divertido e informal',
    'General question': 'Pregunta general',
    'Group decks by class, unit or event': 'Agrupa barajas por clase, unidad o evento',
    'Hard': 'Difícil',
    'How many': 'Cuántas',
    'Install the Add-in': 'Instalar el complemento',
    'Launch a Question': 'Lanzar una pregunta',
    'Live Results': 'Resultados en vivo',
    'Loading workspace…': 'Cargando espacio de trabajo…',
    'Loading…': 'Cargando…',
    'Make a copy of this set as a different product.': 'Haz una copia de este conjunto como otro producto.',
    'Manage members and invites for your workspace.': 'Gestiona miembros e invitaciones de tu espacio de trabajo.',
    'Maximize results (great for projecting)': 'Maximizar resultados (ideal para proyectar)',
    'Medium': 'Media',
    'Message': 'Mensaje',
    'New to PollSlide?': '¿Nuevo en PollSlide?',
    'Newest': 'Más recientes',
    'No presentations yet.': 'Aún no hay presentaciones.',
    'No question live yet — launch one first.': 'Todavía no hay ninguna pregunta en vivo: lanza una primero.',
    'No responses yet.': 'Aún no hay respuestas.',
    'Open the full report': 'Abrir el informe completo',
    'Password': 'Contraseña',
    'PowerPoint Live Results': 'Resultados en vivo en PowerPoint',
    'Present this deck — choose where it goes': 'Presenta esta baraja: elige dónde se muestra',
    'Present — Results Update Live': 'Presentar: los resultados se actualizan en vivo',
    'Presentation name...': 'Nombre de la presentación…',
    'Professional': 'Profesional',
    'QR Code': 'Código QR',
    'Questions from your audience, ranked by upvotes.': 'Preguntas de tu público, ordenadas por votos.',
    'Quick & punchy': 'Breve y directo',
    'Recent': 'Recientes',
    'Rename Presentation': 'Renombrar presentación',
    'Reset Presentation Tally?': '¿Reiniciar el recuento de la presentación?',
    'Reset Tally?': '¿Reiniciar el recuento?',
    'Response Report': 'Informe de respuestas',
    'Responses for this question.': 'Respuestas a esta pregunta.',
    'Restore a deleted presentation': 'Restaurar una presentación eliminada',
    'Results': 'Resultados',
    'Save': 'Guardar',
    'Saved': 'Guardado',
    'Search decks and questions…': 'Buscar barajas y preguntas…',
    'Searches every folder, not just this one': 'Busca en todas las carpetas, no solo en esta',
    'Select a presentation': 'Selecciona una presentación',
    'Select a presentation first.': 'Selecciona primero una presentación.',
    'Select a presentation to copy to:': 'Selecciona la presentación de destino:',
    'Select several decks': 'Seleccionar varias barajas',
    'Send it out': 'Enviarlo',
    'Share link / QR for this survey': 'Enlace / QR para compartir esta encuesta',
    'Share the Q&A link / QR': 'Compartir el enlace / QR de preguntas',
    'Show live poll results inside your presentation deck': 'Muestra los resultados en vivo dentro de tu presentación',
    'Sign In': 'Iniciar sesión',
    'Sign in to manage your presentations.': 'Inicia sesión para gestionar tus presentaciones.',
    'Sort order': 'Orden',
    'Sound effects on/off': 'Activar o desactivar los efectos de sonido',
    'Style': 'Estilo',
    'Subject': 'Asunto',
    'Submit request': 'Enviar solicitud',
    'Switch product': 'Cambiar de producto',
    'Thought-provoking': 'Que invita a pensar',
    'Toggle light/dark': 'Cambiar entre claro y oscuro',
    'Trivia challenge': 'Reto de preguntas',
    'Welcome back': 'Bienvenido de nuevo',
    'Welcome to PollSlide': 'Te damos la bienvenida a PollSlide',
    'What this does': 'Qué hace esto',
    'While you present': 'Mientras presentas',
    'Yes, Reset Everything': 'Sí, reiniciar todo',
    'Yes, Reset Tally': 'Sí, reiniciar el recuento',
    '…or paste lecture notes / an article here': '…o pega aquí apuntes de clase o un artículo',
    '← Back': '← Atrás',
    '← Back to requests': '← Volver a las solicitudes',
    '↑ Click to copy · Replace YOUR_CODE with your session code': '↑ Haz clic para copiar · Sustituye YOUR_CODE por el código de tu sesión',
    '↺ Clear all questions': '↺ Borrar todas las preguntas',
    '↺ Reset All Tallies': '↺ Reiniciar todos los recuentos',
    '▶ Present': '▶ Presentar',
    '✉️ Email it': '✉️ Enviarlo por correo',
    '✉️ Open in my mail app': '✉️ Abrir en mi aplicación de correo',
    '✕ Close': '✕ Cerrar',
    '✨ Ask Polly': '✨ Pregúntale a Polly',
    '✨ Generate': '✨ Generar',
    '✨ Polly': '✨ Polly',
    '⬇ CSV': '⬇ CSV',
    '👥 Team admin': '👥 Administrar equipo',
    '👥 Teams: Off': '👥 Equipos: desactivado',
    '💬 Audience Q&A': '💬 Preguntas del público',
    '💬 Q&A': '💬 Preguntas',
    '📁 Move': '📁 Mover',
    '📁 New folder': '📁 Nueva carpeta',
    '📄 Upload PDF': '📄 Subir PDF',
    '📊 Report': '📊 Informe',
    '📋 Copy this line': '📋 Copiar esta línea',
    '📋 Put this under the QR on your slide': '📋 Pon esto debajo del QR en tu diapositiva',
    '📚 Study now': '📚 Estudiar ahora',
    '📚 Study this deck': '📚 Estudiar esta baraja',
    '📥 Shared with me': '📥 Compartido conmigo',
    '📦 Archive': '📦 Archivar',
    '📦 Archived': '📦 Archivadas',
    '🔗 Share': '🔗 Compartir',
    '🔗 Share Q&A': '🔗 Compartir preguntas',
    '🖥️ Big screen': '🖥️ Pantalla grande',
    '🖨 Print / PDF': '🖨 Imprimir / PDF',
    '🗄 History — saved sessions': '🗄 Historial: sesiones guardadas',
    '🗑 Recently deleted': '🗑 Eliminadas recientemente',
    'Language': 'Idioma',
    "Connect Mac App": "Conectar la app de Mac",
    "Team admin": "Administrar equipo",
    "History (saved data)": "Historial (datos guardados)",
    "See plans & upgrade": "Ver planes y mejorar",
    "PowerPoint live results": "Resultados en vivo en PowerPoint",
    "Setup guide": "Guía de configuración",
    "System status": "Estado del sistema",
    "Delete my account": "Eliminar mi cuenta",
    "Support Chat": "Chat de soporte",
    "Code": "Código",
    "Display": "Pantalla",
    "Enter a session code.": "Escribe un código de sesión.",
    "Full screen": "Pantalla completa",
    "Go full screen (hides browser tabs and menu)": "Pantalla completa (oculta las pestañas y el menú del navegador)",
    "Hides browser chrome": "Oculta la interfaz del navegador",
    "Keeps tabs and menu": "Mantiene las pestañas y el menú",
    "Leave": "Salir",
    "Live results": "Resultados en vivo",
    "Session code": "Código de sesión",
    "Session not found. Check the code and try again.": "No se encontró la sesión. Revisa el código e inténtalo de nuevo.",
    "Stay in window": "Quedarse en la ventana",
    "Waiting for first answer…": "Esperando la primera respuesta…",
    "Waiting for responses…": "Esperando respuestas…",
    "Watch live →": "Ver en vivo →",
    "You're in. Waiting for the presenter…": "Ya estás dentro. Esperando al presentador…",
    "responses": "respuestas",
    "🎪 WARM-UP · JUST FOR FUN": "🎪 CALENTAMIENTO · SOLO POR DIVERSIÓN",
    "🎪 Warm-up: On": "🎪 Calentamiento: activado",
    'Interface language changed.': 'Idioma de la interfaz cambiado.',
  },

  de: {
    '(be as specific as you like — ⌘/Ctrl+Enter to generate)': '(so genau du magst — ⌘/Strg+Enter zum Erzeugen)',
    '+ Add Question': '+ Frage hinzufügen',
    '+ Create New': '+ Neu erstellen',
    '+ Create Your First Presentation': '+ Erstelle deine erste Präsentation',
    '+ New request': '+ Neue Anfrage',
    '0 selected': '0 ausgewählt',
    'Account': 'Konto',
    'Alternative: Embed in Browser / OBS / Companion': 'Alternative: In Browser / OBS / Companion einbetten',
    'Any': 'Beliebig',
    'Audience Q&A — questions & upvotes': 'Publikumsfragen — Fragen und Stimmen',
    'Auto': 'Automatisch',
    'Billing': 'Abrechnung',
    'Brief summary': 'Kurze Zusammenfassung',
    'Bug report': 'Fehlerbericht',
    'Cancel': 'Abbrechen',
    'Category': 'Kategorie',
    'Close': 'Schließen',
    'Connect in PowerPoint': 'In PowerPoint verbinden',
    'Copy Link': 'Link kopieren',
    'Copy Question(s) To...': 'Frage(n) kopieren nach…',
    'Copy to another tab': 'In einen anderen Tab kopieren',
    'Decks other people have shared with you': 'Decks, die andere mit dir geteilt haben',
    "Decks you've put away without deleting": 'Decks, die du weggelegt, aber nicht gelöscht hast',
    'Delete': 'Löschen',
    'Delete Presentation?': 'Präsentation löschen?',
    'Delete all questions for this event': 'Alle Fragen dieser Veranstaltung löschen',
    'Describe a topic and Polly drafts ready-to-go questions.': 'Beschreibe ein Thema, und Polly entwirft fertige Fragen.',
    'Describe it (at least 10 characters)…': 'Beschreibe es (mindestens 10 Zeichen)…',
    'Difficulty': 'Schwierigkeit',
    'Drag to resize': 'Zum Ändern der Größe ziehen',
    'Duplicate': 'Duplizieren',
    'Duplicate Presentation?': 'Präsentation duplizieren?',
    'Easy': 'Leicht',
    'Email address': 'E-Mail-Adresse',
    'Email this survey': 'Diese Umfrage per E-Mail senden',
    'Enter a new name below.': 'Gib unten einen neuen Namen ein.',
    'Everything else': 'Alles Weitere',
    'Feature request': 'Funktionswunsch',
    'Full setup guide →': 'Vollständige Einrichtungsanleitung →',
    'Fun & casual': 'Locker und unterhaltsam',
    'General question': 'Allgemeine Frage',
    'Group decks by class, unit or event': 'Decks nach Klasse, Einheit oder Veranstaltung gruppieren',
    'Hard': 'Schwer',
    'How many': 'Wie viele',
    'Install the Add-in': 'Add-in installieren',
    'Launch a Question': 'Frage starten',
    'Live Results': 'Live-Ergebnisse',
    'Loading workspace…': 'Arbeitsbereich wird geladen…',
    'Loading…': 'Lädt…',
    'Make a copy of this set as a different product.': 'Kopiere diesen Satz als anderes Produkt.',
    'Manage members and invites for your workspace.': 'Mitglieder und Einladungen deines Arbeitsbereichs verwalten.',
    'Maximize results (great for projecting)': 'Ergebnisse maximieren (gut zum Projizieren)',
    'Medium': 'Mittel',
    'Message': 'Nachricht',
    'New to PollSlide?': 'Neu bei PollSlide?',
    'Newest': 'Neueste',
    'No presentations yet.': 'Noch keine Präsentationen.',
    'No question live yet — launch one first.': 'Noch keine Frage live — starte zuerst eine.',
    'No responses yet.': 'Noch keine Antworten.',
    'Open the full report': 'Vollständigen Bericht öffnen',
    'Password': 'Passwort',
    'PowerPoint Live Results': 'PowerPoint-Live-Ergebnisse',
    'Present this deck — choose where it goes': 'Dieses Deck präsentieren — wähle, wo es erscheint',
    'Present — Results Update Live': 'Präsentieren — Ergebnisse aktualisieren sich live',
    'Presentation name...': 'Name der Präsentation…',
    'Professional': 'Professionell',
    'QR Code': 'QR-Code',
    'Questions from your audience, ranked by upvotes.': 'Fragen aus dem Publikum, nach Stimmen sortiert.',
    'Quick & punchy': 'Kurz und knackig',
    'Recent': 'Zuletzt',
    'Rename Presentation': 'Präsentation umbenennen',
    'Reset Presentation Tally?': 'Zählung der Präsentation zurücksetzen?',
    'Reset Tally?': 'Zählung zurücksetzen?',
    'Response Report': 'Antwortbericht',
    'Responses for this question.': 'Antworten auf diese Frage.',
    'Restore a deleted presentation': 'Gelöschte Präsentation wiederherstellen',
    'Results': 'Ergebnisse',
    'Save': 'Speichern',
    'Saved': 'Gespeichert',
    'Search decks and questions…': 'Decks und Fragen durchsuchen…',
    'Searches every folder, not just this one': 'Durchsucht alle Ordner, nicht nur diesen',
    'Select a presentation': 'Präsentation auswählen',
    'Select a presentation first.': 'Wähle zuerst eine Präsentation.',
    'Select a presentation to copy to:': 'Wähle die Zielpräsentation:',
    'Select several decks': 'Mehrere Decks auswählen',
    'Send it out': 'Verschicken',
    'Share link / QR for this survey': 'Link / QR zum Teilen dieser Umfrage',
    'Share the Q&A link / QR': 'Link / QR für Publikumsfragen teilen',
    'Show live poll results inside your presentation deck': 'Live-Ergebnisse direkt in deiner Präsentation zeigen',
    'Sign In': 'Anmelden',
    'Sign in to manage your presentations.': 'Melde dich an, um deine Präsentationen zu verwalten.',
    'Sort order': 'Sortierung',
    'Sound effects on/off': 'Soundeffekte ein/aus',
    'Style': 'Stil',
    'Subject': 'Betreff',
    'Submit request': 'Anfrage senden',
    'Switch product': 'Produkt wechseln',
    'Thought-provoking': 'Zum Nachdenken',
    'Toggle light/dark': 'Hell/Dunkel umschalten',
    'Trivia challenge': 'Quiz-Challenge',
    'Welcome back': 'Willkommen zurück',
    'Welcome to PollSlide': 'Willkommen bei PollSlide',
    'What this does': 'Was das bewirkt',
    'While you present': 'Während du präsentierst',
    'Yes, Reset Everything': 'Ja, alles zurücksetzen',
    'Yes, Reset Tally': 'Ja, Zählung zurücksetzen',
    '…or paste lecture notes / an article here': '…oder füge hier Vorlesungsnotizen oder einen Artikel ein',
    '← Back': '← Zurück',
    '← Back to requests': '← Zurück zu den Anfragen',
    '↑ Click to copy · Replace YOUR_CODE with your session code': '↑ Zum Kopieren klicken · Ersetze YOUR_CODE durch deinen Sitzungscode',
    '↺ Clear all questions': '↺ Alle Fragen löschen',
    '↺ Reset All Tallies': '↺ Alle Zählungen zurücksetzen',
    '▶ Present': '▶ Präsentieren',
    '✉️ Email it': '✉️ Per E-Mail senden',
    '✉️ Open in my mail app': '✉️ In meinem E-Mail-Programm öffnen',
    '✕ Close': '✕ Schließen',
    '✨ Ask Polly': '✨ Polly fragen',
    '✨ Generate': '✨ Erzeugen',
    '✨ Polly': '✨ Polly',
    '⬇ CSV': '⬇ CSV',
    '👥 Team admin': '👥 Teamverwaltung',
    '👥 Teams: Off': '👥 Teams: aus',
    '💬 Audience Q&A': '💬 Publikumsfragen',
    '💬 Q&A': '💬 Fragen',
    '📁 Move': '📁 Verschieben',
    '📁 New folder': '📁 Neuer Ordner',
    '📄 Upload PDF': '📄 PDF hochladen',
    '📊 Report': '📊 Bericht',
    '📋 Copy this line': '📋 Diese Zeile kopieren',
    '📋 Put this under the QR on your slide': '📋 Setze das unter den QR-Code auf deiner Folie',
    '📚 Study now': '📚 Jetzt lernen',
    '📚 Study this deck': '📚 Dieses Deck lernen',
    '📥 Shared with me': '📥 Mit mir geteilt',
    '📦 Archive': '📦 Archivieren',
    '📦 Archived': '📦 Archiviert',
    '🔗 Share': '🔗 Teilen',
    '🔗 Share Q&A': '🔗 Publikumsfragen teilen',
    '🖥️ Big screen': '🖥️ Großer Bildschirm',
    '🖨 Print / PDF': '🖨 Drucken / PDF',
    '🗄 History — saved sessions': '🗄 Verlauf — gespeicherte Sitzungen',
    '🗑 Recently deleted': '🗑 Kürzlich gelöscht',
    'Language': 'Sprache',
    "Connect Mac App": "Mac-App verbinden",
    "Team admin": "Teamverwaltung",
    "History (saved data)": "Verlauf (gespeicherte Daten)",
    "See plans & upgrade": "Tarife ansehen und upgraden",
    "PowerPoint live results": "PowerPoint-Live-Ergebnisse",
    "Setup guide": "Einrichtungsanleitung",
    "System status": "Systemstatus",
    "Delete my account": "Mein Konto löschen",
    "Support Chat": "Support-Chat",
    "Code": "Code",
    "Display": "Anzeige",
    "Enter a session code.": "Gib einen Sitzungscode ein.",
    "Full screen": "Vollbild",
    "Go full screen (hides browser tabs and menu)": "Vollbild (blendet Browser-Tabs und Menü aus)",
    "Hides browser chrome": "Blendet die Browser-Oberfläche aus",
    "Keeps tabs and menu": "Behält Tabs und Menü",
    "Leave": "Verlassen",
    "Live results": "Live-Ergebnisse",
    "Session code": "Sitzungscode",
    "Session not found. Check the code and try again.": "Sitzung nicht gefunden. Prüfe den Code und versuche es erneut.",
    "Stay in window": "Im Fenster bleiben",
    "Waiting for first answer…": "Warten auf die erste Antwort…",
    "Waiting for responses…": "Warten auf Antworten…",
    "Watch live →": "Live ansehen →",
    "You're in. Waiting for the presenter…": "Du bist dabei. Warten auf die präsentierende Person…",
    "responses": "Antworten",
    "🎪 WARM-UP · JUST FOR FUN": "🎪 AUFWÄRMEN · NUR ZUM SPASS",
    "🎪 Warm-up: On": "🎪 Aufwärmen: an",
    'Interface language changed.': 'Sprache der Oberfläche geändert.',
  },

  fr: {
    '(be as specific as you like — ⌘/Ctrl+Enter to generate)': '(soyez aussi précis que vous voulez — ⌘/Ctrl+Entrée pour générer)',
    '+ Add Question': '+ Ajouter une question',
    '+ Create New': '+ Créer',
    '+ Create Your First Presentation': '+ Créez votre première présentation',
    '+ New request': '+ Nouvelle demande',
    '0 selected': '0 sélectionné',
    'Account': 'Compte',
    'Alternative: Embed in Browser / OBS / Companion': 'Autre option : intégrer au navigateur / OBS / Companion',
    'Any': 'Indifférent',
    'Audience Q&A — questions & upvotes': 'Questions du public — questions et votes',
    'Auto': 'Automatique',
    'Billing': 'Facturation',
    'Brief summary': 'Résumé court',
    'Bug report': 'Signaler un bug',
    'Cancel': 'Annuler',
    'Category': 'Catégorie',
    'Close': 'Fermer',
    'Connect in PowerPoint': 'Connecter dans PowerPoint',
    'Copy Link': 'Copier le lien',
    'Copy Question(s) To...': 'Copier la ou les questions vers…',
    'Copy to another tab': 'Copier vers un autre onglet',
    'Decks other people have shared with you': 'Jeux que d’autres ont partagés avec vous',
    "Decks you've put away without deleting": 'Jeux que vous avez rangés sans les supprimer',
    'Delete': 'Supprimer',
    'Delete Presentation?': 'Supprimer la présentation ?',
    'Delete all questions for this event': 'Supprimer toutes les questions de cet événement',
    'Describe a topic and Polly drafts ready-to-go questions.': 'Décrivez un sujet et Polly rédige des questions prêtes à l’emploi.',
    'Describe it (at least 10 characters)…': 'Décrivez-le (au moins 10 caractères)…',
    'Difficulty': 'Difficulté',
    'Drag to resize': 'Faites glisser pour redimensionner',
    'Duplicate': 'Dupliquer',
    'Duplicate Presentation?': 'Dupliquer la présentation ?',
    'Easy': 'Facile',
    'Email address': 'Adresse e-mail',
    'Email this survey': 'Envoyer ce sondage par e-mail',
    'Enter a new name below.': 'Saisissez un nouveau nom ci-dessous.',
    'Everything else': 'Tout le reste',
    'Feature request': 'Demande de fonctionnalité',
    'Full setup guide →': 'Guide de configuration complet →',
    'Fun & casual': 'Léger et décontracté',
    'General question': 'Question générale',
    'Group decks by class, unit or event': 'Regroupez les jeux par classe, chapitre ou événement',
    'Hard': 'Difficile',
    'How many': 'Combien',
    'Install the Add-in': 'Installer le complément',
    'Launch a Question': 'Lancer une question',
    'Live Results': 'Résultats en direct',
    'Loading workspace…': 'Chargement de l’espace de travail…',
    'Loading…': 'Chargement…',
    'Make a copy of this set as a different product.': 'Copiez cet ensemble sous un autre produit.',
    'Manage members and invites for your workspace.': 'Gérez les membres et les invitations de votre espace de travail.',
    'Maximize results (great for projecting)': 'Agrandir les résultats (idéal pour projeter)',
    'Medium': 'Moyenne',
    'Message': 'Message',
    'New to PollSlide?': 'Nouveau sur PollSlide ?',
    'Newest': 'Plus récents',
    'No presentations yet.': 'Aucune présentation pour l’instant.',
    'No question live yet — launch one first.': 'Aucune question en direct — lancez-en une d’abord.',
    'No responses yet.': 'Aucune réponse pour l’instant.',
    'Open the full report': 'Ouvrir le rapport complet',
    'Password': 'Mot de passe',
    'PowerPoint Live Results': 'Résultats en direct dans PowerPoint',
    'Present this deck — choose where it goes': 'Présenter ce jeu — choisissez où il s’affiche',
    'Present — Results Update Live': 'Présenter — les résultats se mettent à jour en direct',
    'Presentation name...': 'Nom de la présentation…',
    'Professional': 'Professionnel',
    'QR Code': 'QR code',
    'Questions from your audience, ranked by upvotes.': 'Questions de votre public, classées par votes.',
    'Quick & punchy': 'Court et percutant',
    'Recent': 'Récents',
    'Rename Presentation': 'Renommer la présentation',
    'Reset Presentation Tally?': 'Réinitialiser le décompte de la présentation ?',
    'Reset Tally?': 'Réinitialiser le décompte ?',
    'Response Report': 'Rapport des réponses',
    'Responses for this question.': 'Réponses à cette question.',
    'Restore a deleted presentation': 'Restaurer une présentation supprimée',
    'Results': 'Résultats',
    'Save': 'Enregistrer',
    'Saved': 'Enregistré',
    'Search decks and questions…': 'Rechercher des jeux et des questions…',
    'Searches every folder, not just this one': 'Cherche dans tous les dossiers, pas seulement celui-ci',
    'Select a presentation': 'Sélectionnez une présentation',
    'Select a presentation first.': 'Sélectionnez d’abord une présentation.',
    'Select a presentation to copy to:': 'Sélectionnez la présentation de destination :',
    'Select several decks': 'Sélectionner plusieurs jeux',
    'Send it out': 'L’envoyer',
    'Share link / QR for this survey': 'Lien / QR pour partager ce sondage',
    'Share the Q&A link / QR': 'Partager le lien / QR des questions',
    'Show live poll results inside your presentation deck': 'Affichez les résultats en direct dans votre présentation',
    'Sign In': 'Se connecter',
    'Sign in to manage your presentations.': 'Connectez-vous pour gérer vos présentations.',
    'Sort order': 'Tri',
    'Sound effects on/off': 'Effets sonores activés/désactivés',
    'Style': 'Style',
    'Subject': 'Objet',
    'Submit request': 'Envoyer la demande',
    'Switch product': 'Changer de produit',
    'Thought-provoking': 'Qui fait réfléchir',
    'Toggle light/dark': 'Basculer clair/sombre',
    'Trivia challenge': 'Défi quiz',
    'Welcome back': 'Bon retour',
    'Welcome to PollSlide': 'Bienvenue sur PollSlide',
    'What this does': 'Ce que ça fait',
    'While you present': 'Pendant que vous présentez',
    'Yes, Reset Everything': 'Oui, tout réinitialiser',
    'Yes, Reset Tally': 'Oui, réinitialiser le décompte',
    '…or paste lecture notes / an article here': '…ou collez ici des notes de cours ou un article',
    '← Back': '← Retour',
    '← Back to requests': '← Retour aux demandes',
    '↑ Click to copy · Replace YOUR_CODE with your session code': '↑ Cliquez pour copier · Remplacez YOUR_CODE par le code de votre session',
    '↺ Clear all questions': '↺ Effacer toutes les questions',
    '↺ Reset All Tallies': '↺ Réinitialiser tous les décomptes',
    '▶ Present': '▶ Présenter',
    '✉️ Email it': '✉️ Envoyer par e-mail',
    '✉️ Open in my mail app': '✉️ Ouvrir dans ma messagerie',
    '✕ Close': '✕ Fermer',
    '✨ Ask Polly': '✨ Demander à Polly',
    '✨ Generate': '✨ Générer',
    '✨ Polly': '✨ Polly',
    '⬇ CSV': '⬇ CSV',
    '👥 Team admin': '👥 Administration de l’équipe',
    '👥 Teams: Off': '👥 Équipes : désactivé',
    '💬 Audience Q&A': '💬 Questions du public',
    '💬 Q&A': '💬 Questions',
    '📁 Move': '📁 Déplacer',
    '📁 New folder': '📁 Nouveau dossier',
    '📄 Upload PDF': '📄 Importer un PDF',
    '📊 Report': '📊 Rapport',
    '📋 Copy this line': '📋 Copier cette ligne',
    '📋 Put this under the QR on your slide': '📋 Placez ceci sous le QR de votre diapositive',
    '📚 Study now': '📚 Réviser maintenant',
    '📚 Study this deck': '📚 Réviser ce jeu',
    '📥 Shared with me': '📥 Partagé avec moi',
    '📦 Archive': '📦 Archiver',
    '📦 Archived': '📦 Archivés',
    '🔗 Share': '🔗 Partager',
    '🔗 Share Q&A': '🔗 Partager les questions',
    '🖥️ Big screen': '🖥️ Grand écran',
    '🖨 Print / PDF': '🖨 Imprimer / PDF',
    '🗄 History — saved sessions': '🗄 Historique — sessions enregistrées',
    '🗑 Recently deleted': '🗑 Supprimés récemment',
    'Language': 'Langue',
    "Connect Mac App": "Connecter l’app Mac",
    "Team admin": "Administration de l’équipe",
    "History (saved data)": "Historique (données enregistrées)",
    "See plans & upgrade": "Voir les offres et passer à un forfait supérieur",
    "PowerPoint live results": "Résultats en direct dans PowerPoint",
    "Setup guide": "Guide de configuration",
    "System status": "État du système",
    "Delete my account": "Supprimer mon compte",
    "Support Chat": "Chat d’assistance",
    "Code": "Code",
    "Display": "Affichage",
    "Enter a session code.": "Saisissez un code de session.",
    "Full screen": "Plein écran",
    "Go full screen (hides browser tabs and menu)": "Passer en plein écran (masque les onglets et le menu du navigateur)",
    "Hides browser chrome": "Masque l’interface du navigateur",
    "Keeps tabs and menu": "Conserve les onglets et le menu",
    "Leave": "Quitter",
    "Live results": "Résultats en direct",
    "Session code": "Code de session",
    "Session not found. Check the code and try again.": "Session introuvable. Vérifiez le code et réessayez.",
    "Stay in window": "Rester dans la fenêtre",
    "Waiting for first answer…": "En attente de la première réponse…",
    "Waiting for responses…": "En attente de réponses…",
    "Watch live →": "Suivre en direct →",
    "You're in. Waiting for the presenter…": "Vous y êtes. En attente du présentateur…",
    "responses": "réponses",
    "🎪 WARM-UP · JUST FOR FUN": "🎪 ÉCHAUFFEMENT · JUSTE POUR LE PLAISIR",
    "🎪 Warm-up: On": "🎪 Échauffement : activé",
    'Interface language changed.': 'Langue de l’interface modifiée.',
  },

  pt: {
    '(be as specific as you like — ⌘/Ctrl+Enter to generate)': '(seja tão específico quanto quiser — ⌘/Ctrl+Enter para gerar)',
    '+ Add Question': '+ Adicionar pergunta',
    '+ Create New': '+ Criar novo',
    '+ Create Your First Presentation': '+ Crie a sua primeira apresentação',
    '+ New request': '+ Novo pedido',
    '0 selected': '0 selecionados',
    'Account': 'Conta',
    'Alternative: Embed in Browser / OBS / Companion': 'Alternativa: incorporar no navegador / OBS / Companion',
    'Any': 'Qualquer',
    'Audience Q&A — questions & upvotes': 'Perguntas do público — perguntas e votos',
    'Auto': 'Automático',
    'Billing': 'Faturação',
    'Brief summary': 'Resumo breve',
    'Bug report': 'Relatar um erro',
    'Cancel': 'Cancelar',
    'Category': 'Categoria',
    'Close': 'Fechar',
    'Connect in PowerPoint': 'Ligar no PowerPoint',
    'Copy Link': 'Copiar ligação',
    'Copy Question(s) To...': 'Copiar pergunta(s) para…',
    'Copy to another tab': 'Copiar para outro separador',
    'Decks other people have shared with you': 'Baralhos que outras pessoas partilharam consigo',
    "Decks you've put away without deleting": 'Baralhos que guardou sem apagar',
    'Delete': 'Eliminar',
    'Delete Presentation?': 'Eliminar a apresentação?',
    'Delete all questions for this event': 'Eliminar todas as perguntas deste evento',
    'Describe a topic and Polly drafts ready-to-go questions.': 'Descreva um tema e a Polly redige perguntas prontas a usar.',
    'Describe it (at least 10 characters)…': 'Descreva-o (pelo menos 10 caracteres)…',
    'Difficulty': 'Dificuldade',
    'Drag to resize': 'Arraste para redimensionar',
    'Duplicate': 'Duplicar',
    'Duplicate Presentation?': 'Duplicar a apresentação?',
    'Easy': 'Fácil',
    'Email address': 'Endereço de e-mail',
    'Email this survey': 'Enviar este inquérito por e-mail',
    'Enter a new name below.': 'Escreva um novo nome abaixo.',
    'Everything else': 'Tudo o resto',
    'Feature request': 'Sugestão de funcionalidade',
    'Full setup guide →': 'Guia de configuração completo →',
    'Fun & casual': 'Divertido e descontraído',
    'General question': 'Pergunta geral',
    'Group decks by class, unit or event': 'Agrupe baralhos por turma, unidade ou evento',
    'Hard': 'Difícil',
    'How many': 'Quantas',
    'Install the Add-in': 'Instalar o suplemento',
    'Launch a Question': 'Lançar uma pergunta',
    'Live Results': 'Resultados ao vivo',
    'Loading workspace…': 'A carregar a área de trabalho…',
    'Loading…': 'A carregar…',
    'Make a copy of this set as a different product.': 'Faça uma cópia deste conjunto como outro produto.',
    'Manage members and invites for your workspace.': 'Faça a gestão de membros e convites da sua área de trabalho.',
    'Maximize results (great for projecting)': 'Maximizar resultados (ótimo para projetar)',
    'Medium': 'Média',
    'Message': 'Mensagem',
    'New to PollSlide?': 'Novo no PollSlide?',
    'Newest': 'Mais recentes',
    'No presentations yet.': 'Ainda não há apresentações.',
    'No question live yet — launch one first.': 'Ainda não há nenhuma pergunta ao vivo — lance uma primeiro.',
    'No responses yet.': 'Ainda não há respostas.',
    'Open the full report': 'Abrir o relatório completo',
    'Password': 'Palavra-passe',
    'PowerPoint Live Results': 'Resultados ao vivo no PowerPoint',
    'Present this deck — choose where it goes': 'Apresentar este baralho — escolha onde aparece',
    'Present — Results Update Live': 'Apresentar — os resultados atualizam ao vivo',
    'Presentation name...': 'Nome da apresentação…',
    'Professional': 'Profissional',
    'QR Code': 'Código QR',
    'Questions from your audience, ranked by upvotes.': 'Perguntas do seu público, ordenadas por votos.',
    'Quick & punchy': 'Curto e direto',
    'Recent': 'Recentes',
    'Rename Presentation': 'Mudar o nome da apresentação',
    'Reset Presentation Tally?': 'Repor a contagem da apresentação?',
    'Reset Tally?': 'Repor a contagem?',
    'Response Report': 'Relatório de respostas',
    'Responses for this question.': 'Respostas a esta pergunta.',
    'Restore a deleted presentation': 'Restaurar uma apresentação eliminada',
    'Results': 'Resultados',
    'Save': 'Guardar',
    'Saved': 'Guardado',
    'Search decks and questions…': 'Procurar baralhos e perguntas…',
    'Searches every folder, not just this one': 'Procura em todas as pastas, não apenas nesta',
    'Select a presentation': 'Selecione uma apresentação',
    'Select a presentation first.': 'Selecione primeiro uma apresentação.',
    'Select a presentation to copy to:': 'Selecione a apresentação de destino:',
    'Select several decks': 'Selecionar vários baralhos',
    'Send it out': 'Enviar',
    'Share link / QR for this survey': 'Ligação / QR para partilhar este inquérito',
    'Share the Q&A link / QR': 'Partilhar a ligação / QR das perguntas',
    'Show live poll results inside your presentation deck': 'Mostre os resultados ao vivo dentro da sua apresentação',
    'Sign In': 'Iniciar sessão',
    'Sign in to manage your presentations.': 'Inicie sessão para gerir as suas apresentações.',
    'Sort order': 'Ordenação',
    'Sound effects on/off': 'Ativar ou desativar os efeitos sonoros',
    'Style': 'Estilo',
    'Subject': 'Assunto',
    'Submit request': 'Enviar pedido',
    'Switch product': 'Mudar de produto',
    'Thought-provoking': 'Que faz pensar',
    'Toggle light/dark': 'Alternar claro/escuro',
    'Trivia challenge': 'Desafio de perguntas',
    'Welcome back': 'Bem-vindo de volta',
    'Welcome to PollSlide': 'Bem-vindo ao PollSlide',
    'What this does': 'O que isto faz',
    'While you present': 'Enquanto apresenta',
    'Yes, Reset Everything': 'Sim, repor tudo',
    'Yes, Reset Tally': 'Sim, repor a contagem',
    '…or paste lecture notes / an article here': '…ou cole aqui apontamentos de aula ou um artigo',
    '← Back': '← Voltar',
    '← Back to requests': '← Voltar aos pedidos',
    '↑ Click to copy · Replace YOUR_CODE with your session code': '↑ Clique para copiar · Substitua YOUR_CODE pelo código da sua sessão',
    '↺ Clear all questions': '↺ Limpar todas as perguntas',
    '↺ Reset All Tallies': '↺ Repor todas as contagens',
    '▶ Present': '▶ Apresentar',
    '✉️ Email it': '✉️ Enviar por e-mail',
    '✉️ Open in my mail app': '✉️ Abrir na minha aplicação de e-mail',
    '✕ Close': '✕ Fechar',
    '✨ Ask Polly': '✨ Perguntar à Polly',
    '✨ Generate': '✨ Gerar',
    '✨ Polly': '✨ Polly',
    '⬇ CSV': '⬇ CSV',
    '👥 Team admin': '👥 Gestão da equipa',
    '👥 Teams: Off': '👥 Equipas: desligado',
    '💬 Audience Q&A': '💬 Perguntas do público',
    '💬 Q&A': '💬 Perguntas',
    '📁 Move': '📁 Mover',
    '📁 New folder': '📁 Nova pasta',
    '📄 Upload PDF': '📄 Carregar PDF',
    '📊 Report': '📊 Relatório',
    '📋 Copy this line': '📋 Copiar esta linha',
    '📋 Put this under the QR on your slide': '📋 Coloque isto por baixo do QR no seu diapositivo',
    '📚 Study now': '📚 Estudar agora',
    '📚 Study this deck': '📚 Estudar este baralho',
    '📥 Shared with me': '📥 Partilhado comigo',
    '📦 Archive': '📦 Arquivar',
    '📦 Archived': '📦 Arquivados',
    '🔗 Share': '🔗 Partilhar',
    '🔗 Share Q&A': '🔗 Partilhar perguntas',
    '🖥️ Big screen': '🖥️ Ecrã grande',
    '🖨 Print / PDF': '🖨 Imprimir / PDF',
    '🗄 History — saved sessions': '🗄 Histórico — sessões guardadas',
    '🗑 Recently deleted': '🗑 Eliminados recentemente',
    'Language': 'Idioma',
    "Connect Mac App": "Ligar a app de Mac",
    "Team admin": "Gestão da equipa",
    "History (saved data)": "Histórico (dados guardados)",
    "See plans & upgrade": "Ver planos e fazer upgrade",
    "PowerPoint live results": "Resultados ao vivo no PowerPoint",
    "Setup guide": "Guia de configuração",
    "System status": "Estado do sistema",
    "Delete my account": "Eliminar a minha conta",
    "Support Chat": "Chat de apoio",
    "Code": "Código",
    "Display": "Ecrã",
    "Enter a session code.": "Introduza um código de sessão.",
    "Full screen": "Ecrã inteiro",
    "Go full screen (hides browser tabs and menu)": "Ecrã inteiro (oculta os separadores e o menu do navegador)",
    "Hides browser chrome": "Oculta a interface do navegador",
    "Keeps tabs and menu": "Mantém os separadores e o menu",
    "Leave": "Sair",
    "Live results": "Resultados ao vivo",
    "Session code": "Código da sessão",
    "Session not found. Check the code and try again.": "Sessão não encontrada. Verifique o código e tente novamente.",
    "Stay in window": "Ficar na janela",
    "Waiting for first answer…": "A aguardar a primeira resposta…",
    "Waiting for responses…": "A aguardar respostas…",
    "Watch live →": "Ver ao vivo →",
    "You're in. Waiting for the presenter…": "Já entrou. A aguardar o apresentador…",
    "responses": "respostas",
    "🎪 WARM-UP · JUST FOR FUN": "🎪 AQUECIMENTO · SÓ POR DIVERSÃO",
    "🎪 Warm-up: On": "🎪 Aquecimento: ligado",
    'Interface language changed.': 'Idioma da interface alterado.',
  },

  it: {
    '(be as specific as you like — ⌘/Ctrl+Enter to generate)': '(sii specifico quanto vuoi — ⌘/Ctrl+Invio per generare)',
    '+ Add Question': '+ Aggiungi domanda',
    '+ Create New': '+ Crea nuovo',
    '+ Create Your First Presentation': '+ Crea la tua prima presentazione',
    '+ New request': '+ Nuova richiesta',
    '0 selected': '0 selezionati',
    'Account': 'Account',
    'Alternative: Embed in Browser / OBS / Companion': 'In alternativa: incorpora nel browser / OBS / Companion',
    'Any': 'Qualsiasi',
    'Audience Q&A — questions & upvotes': 'Domande del pubblico — domande e voti',
    'Auto': 'Automatico',
    'Billing': 'Fatturazione',
    'Brief summary': 'Breve riassunto',
    'Bug report': 'Segnalazione di un errore',
    'Cancel': 'Annulla',
    'Category': 'Categoria',
    'Close': 'Chiudi',
    'Connect in PowerPoint': 'Collega in PowerPoint',
    'Copy Link': 'Copia link',
    'Copy Question(s) To...': 'Copia le domande in…',
    'Copy to another tab': 'Copia in un’altra scheda',
    'Decks other people have shared with you': 'Mazzi che altri hanno condiviso con te',
    "Decks you've put away without deleting": 'Mazzi che hai messo da parte senza eliminarli',
    'Delete': 'Elimina',
    'Delete Presentation?': 'Eliminare la presentazione?',
    'Delete all questions for this event': 'Elimina tutte le domande di questo evento',
    'Describe a topic and Polly drafts ready-to-go questions.': 'Descrivi un argomento e Polly prepara domande pronte all’uso.',
    'Describe it (at least 10 characters)…': 'Descrivilo (almeno 10 caratteri)…',
    'Difficulty': 'Difficoltà',
    'Drag to resize': 'Trascina per ridimensionare',
    'Duplicate': 'Duplica',
    'Duplicate Presentation?': 'Duplicare la presentazione?',
    'Easy': 'Facile',
    'Email address': 'Indirizzo e-mail',
    'Email this survey': 'Invia questo sondaggio per e-mail',
    'Enter a new name below.': 'Inserisci un nuovo nome qui sotto.',
    'Everything else': 'Tutto il resto',
    'Feature request': 'Richiesta di funzionalità',
    'Full setup guide →': 'Guida completa alla configurazione →',
    'Fun & casual': 'Leggero e informale',
    'General question': 'Domanda generica',
    'Group decks by class, unit or event': 'Raggruppa i mazzi per classe, unità o evento',
    'Hard': 'Difficile',
    'How many': 'Quante',
    'Install the Add-in': 'Installa il componente aggiuntivo',
    'Launch a Question': 'Lancia una domanda',
    'Live Results': 'Risultati in diretta',
    'Loading workspace…': 'Caricamento dello spazio di lavoro…',
    'Loading…': 'Caricamento…',
    'Make a copy of this set as a different product.': 'Crea una copia di questo set come prodotto diverso.',
    'Manage members and invites for your workspace.': 'Gestisci membri e inviti del tuo spazio di lavoro.',
    'Maximize results (great for projecting)': 'Ingrandisci i risultati (ottimo da proiettare)',
    'Medium': 'Media',
    'Message': 'Messaggio',
    'New to PollSlide?': 'Nuovo su PollSlide?',
    'Newest': 'Più recenti',
    'No presentations yet.': 'Ancora nessuna presentazione.',
    'No question live yet — launch one first.': 'Nessuna domanda ancora in diretta — lanciane una prima.',
    'No responses yet.': 'Ancora nessuna risposta.',
    'Open the full report': 'Apri il rapporto completo',
    'Password': 'Password',
    'PowerPoint Live Results': 'Risultati in diretta in PowerPoint',
    'Present this deck — choose where it goes': 'Presenta questo mazzo — scegli dove appare',
    'Present — Results Update Live': 'Presenta — i risultati si aggiornano in diretta',
    'Presentation name...': 'Nome della presentazione…',
    'Professional': 'Professionale',
    'QR Code': 'Codice QR',
    'Questions from your audience, ranked by upvotes.': 'Domande del tuo pubblico, ordinate per voti.',
    'Quick & punchy': 'Breve e incisivo',
    'Recent': 'Recenti',
    'Rename Presentation': 'Rinomina presentazione',
    'Reset Presentation Tally?': 'Azzerare il conteggio della presentazione?',
    'Reset Tally?': 'Azzerare il conteggio?',
    'Response Report': 'Rapporto delle risposte',
    'Responses for this question.': 'Risposte a questa domanda.',
    'Restore a deleted presentation': 'Ripristina una presentazione eliminata',
    'Results': 'Risultati',
    'Save': 'Salva',
    'Saved': 'Salvato',
    'Search decks and questions…': 'Cerca mazzi e domande…',
    'Searches every folder, not just this one': 'Cerca in tutte le cartelle, non solo in questa',
    'Select a presentation': 'Seleziona una presentazione',
    'Select a presentation first.': 'Seleziona prima una presentazione.',
    'Select a presentation to copy to:': 'Seleziona la presentazione di destinazione:',
    'Select several decks': 'Seleziona più mazzi',
    'Send it out': 'Invialo',
    'Share link / QR for this survey': 'Link / QR per condividere questo sondaggio',
    'Share the Q&A link / QR': 'Condividi il link / QR delle domande',
    'Show live poll results inside your presentation deck': 'Mostra i risultati in diretta dentro la tua presentazione',
    'Sign In': 'Accedi',
    'Sign in to manage your presentations.': 'Accedi per gestire le tue presentazioni.',
    'Sort order': 'Ordinamento',
    'Sound effects on/off': 'Attiva o disattiva gli effetti sonori',
    'Style': 'Stile',
    'Subject': 'Oggetto',
    'Submit request': 'Invia richiesta',
    'Switch product': 'Cambia prodotto',
    'Thought-provoking': 'Che fa riflettere',
    'Toggle light/dark': 'Alterna chiaro/scuro',
    'Trivia challenge': 'Sfida a quiz',
    'Welcome back': 'Bentornato',
    'Welcome to PollSlide': 'Benvenuto su PollSlide',
    'What this does': 'Che cosa fa',
    'While you present': 'Mentre presenti',
    'Yes, Reset Everything': 'Sì, azzera tutto',
    'Yes, Reset Tally': 'Sì, azzera il conteggio',
    '…or paste lecture notes / an article here': '…oppure incolla qui appunti di lezione o un articolo',
    '← Back': '← Indietro',
    '← Back to requests': '← Torna alle richieste',
    '↑ Click to copy · Replace YOUR_CODE with your session code': '↑ Clicca per copiare · Sostituisci YOUR_CODE con il codice della tua sessione',
    '↺ Clear all questions': '↺ Cancella tutte le domande',
    '↺ Reset All Tallies': '↺ Azzera tutti i conteggi',
    '▶ Present': '▶ Presenta',
    '✉️ Email it': '✉️ Invia per e-mail',
    '✉️ Open in my mail app': '✉️ Apri nella mia app di posta',
    '✕ Close': '✕ Chiudi',
    '✨ Ask Polly': '✨ Chiedi a Polly',
    '✨ Generate': '✨ Genera',
    '✨ Polly': '✨ Polly',
    '⬇ CSV': '⬇ CSV',
    '👥 Team admin': '👥 Gestione del team',
    '👥 Teams: Off': '👥 Team: disattivati',
    '💬 Audience Q&A': '💬 Domande del pubblico',
    '💬 Q&A': '💬 Domande',
    '📁 Move': '📁 Sposta',
    '📁 New folder': '📁 Nuova cartella',
    '📄 Upload PDF': '📄 Carica PDF',
    '📊 Report': '📊 Rapporto',
    '📋 Copy this line': '📋 Copia questa riga',
    '📋 Put this under the QR on your slide': '📋 Metti questo sotto il QR nella tua slide',
    '📚 Study now': '📚 Studia ora',
    '📚 Study this deck': '📚 Studia questo mazzo',
    '📥 Shared with me': '📥 Condivisi con me',
    '📦 Archive': '📦 Archivia',
    '📦 Archived': '📦 Archiviati',
    '🔗 Share': '🔗 Condividi',
    '🔗 Share Q&A': '🔗 Condividi le domande',
    '🖥️ Big screen': '🖥️ Schermo grande',
    '🖨 Print / PDF': '🖨 Stampa / PDF',
    '🗄 History — saved sessions': '🗄 Cronologia — sessioni salvate',
    '🗑 Recently deleted': '🗑 Eliminati di recente',
    'Language': 'Lingua',
    "Connect Mac App": "Collega l’app per Mac",
    "Team admin": "Gestione del team",
    "History (saved data)": "Cronologia (dati salvati)",
    "See plans & upgrade": "Vedi i piani e passa a un piano superiore",
    "PowerPoint live results": "Risultati in diretta in PowerPoint",
    "Setup guide": "Guida alla configurazione",
    "System status": "Stato del sistema",
    "Delete my account": "Elimina il mio account",
    "Support Chat": "Chat di supporto",
    "Code": "Codice",
    "Display": "Schermo",
    "Enter a session code.": "Inserisci un codice sessione.",
    "Full screen": "Schermo intero",
    "Go full screen (hides browser tabs and menu)": "Schermo intero (nasconde le schede e il menu del browser)",
    "Hides browser chrome": "Nasconde l’interfaccia del browser",
    "Keeps tabs and menu": "Mantiene schede e menu",
    "Leave": "Esci",
    "Live results": "Risultati in diretta",
    "Session code": "Codice sessione",
    "Session not found. Check the code and try again.": "Sessione non trovata. Controlla il codice e riprova.",
    "Stay in window": "Resta nella finestra",
    "Waiting for first answer…": "In attesa della prima risposta…",
    "Waiting for responses…": "In attesa di risposte…",
    "Watch live →": "Guarda in diretta →",
    "You're in. Waiting for the presenter…": "Ci sei. In attesa di chi presenta…",
    "responses": "risposte",
    "🎪 WARM-UP · JUST FOR FUN": "🎪 RISCALDAMENTO · SOLO PER DIVERTIMENTO",
    "🎪 Warm-up: On": "🎪 Riscaldamento: attivo",
    'Interface language changed.': 'Lingua dell’interfaccia modificata.',
  },
});
